"""
Copy frontend/src/lib/missionAnalytics.js into static/index.html.

static/index.html is served by app.py / app_live.py without a static-file
mount, so it can't import the ES module. This script inlines the module as
an IIFE exposing `MA.<name>` between the BEGIN/END markers. Run it after
editing missionAnalytics.js:

    python scripts/sync_dashboard_analytics.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "frontend" / "src" / "lib" / "missionAnalytics.js"
DST = ROOT / "static" / "index.html"
BEGIN = "<!-- BEGIN missionAnalytics.js (generated by scripts/sync_dashboard_analytics.py, do not edit) -->"
END = "<!-- END missionAnalytics.js -->"

src = SRC.read_text()
names = re.findall(r"^export (?:const|function|class) (\w+)", src, flags=re.M)
body = re.sub(r"^export (const|function|class) ", r"\1 ", src, flags=re.M)
block = (
    f"{BEGIN}\n<script>\nconst MA = (() => {{\n{body}\n"
    f"return {{ {', '.join(names)} }};\n}})();\n</script>\n{END}"
)

html = DST.read_text()
if BEGIN in html:
    html = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, html, flags=re.S)
else:
    html = html.replace("\n<script>", "\n" + block + "\n<script>", 1)
DST.write_text(html)
print(f"inlined {len(names)} exports into {DST.relative_to(ROOT)}")
